### ISSUE TITLE
Support Google authentication

### ISSUE THREAD

**Issue by nmaro** [nmaro/ooth#4]

**Comment by detrohutt** [comment]
I'm glad to see you're planning on supporting this. Do you have an estimate of when it'll be ready(days, weeks, months)?

**Comment by sw-yx** [comment]
looking forward to this too. i am still not there yet to begin contributing but i will put my hand up to help out when i can.

**Comment by nmaro** [comment]
Hey guys, thanks for writing. It definitely helps to hear that people want a feature to motivate me implementing it. I'll try to get it done within this or next week.

By the way, since I'd like to get a feel as to whether anyone other than me is actually using ooth, so if I may ask: are you using it? Have you tried it out? How did you hear about it? What are your general impressions?

**Comment by detrohutt** [comment]
I haven't tried it yet. I'm actually waiting on Google(or Facebook) authentication in order to use it because I've stopped using password authentication after being convinced by a few different sources that it's obsolete. I believe I found out about ooth by just searching Medium for "javascript authentication" or something similar a few months ago and reading [your ooth article](https://medium.com/the-ideal-system/ooth-user-accounts-for-node-js-93cfcd28ed1a).

Although I haven't used it yet, I did look at most of the source code in this repo to try to get a feel for how it all works and fits together. I was impressed with how clean it all is.

It may help if I tell you my use case... I'm working on a text adventure game with a friend who is not a programmer(he's a writer) so I built a world editor for him to use. We're collaborating remotely so I want to just put the editor online where we can both use it, but I don't want anyone who comes across the site to go deleting our whole world lol. So I just basically want to whitelist 2 accounts using Google or Facebook authentication and otherwise not allow registration.

Also, on an unrelated note, I noticed you use GraphQL and Next.js together.. you may want to check out my [babel-plugin](https://www.npmjs.com/package/babel-plugin-inline-import-graphql-ast), which allows you to use .gql/.graphql files with Next.js.

**Comment by sw-yx** [comment]
as for me, i am personally working through implementing auth with passportjs right now and facing some difficulty with all the configuration (even though this is not my first time with passportjs.. i just got rusty). I do come from the Meteor world so thats why i like the concept of ooth so much but being honest i havent really tried it yet (i last had that node version issue, which is now moot since i upgraded to node 8). I will try it tomorrow. regardless you should do what makes you happy at this early stage in this project as you will def be the #1 user of it

**Comment by wmertens** [comment]
I am in the process of setting up auth and I came to realize that for a
SPA, passportjs is a bad fit. A component like react-google-login is
trivial to add and gives you the token in a callback. You can then send the
token to the server via whatever mechanism you like (graphql in my case) so
the server can verify it and log you in. Passportjs cannot help with any of
those steps.

**Comment by nmaro** [comment]
@wmertens your observation is correct, though Passport.js can actually help with the last step (where the server verifies and logs you in). You just have to pick the right package (i.e. not the one that does the whole oauth process). See https://github.com/jmreyes/passport-google-id-token for google, or https://github.com/drudge/passport-facebook-token for facebook. I used these two in ooth-google and ooth-facebook respectively.

**Comment by nmaro** [comment]
Implemented as a package here: https://github.com/nmaro/ooth/tree/master/packages/ooth-google
Example server-side usage here: https://github.com/nmaro/staart/blob/master/examples/staart/server/ooth.js
Example client-side usage here: https://github.com/nmaro/staart/blob/master/packages/staart/src/components/login-google.js
Working live example: staart.nmr.io/login

**Comment by wmertens** [comment]
Very nice! I'll check these out soonish.
