### ISSUE TITLE
Programmatic API

### ISSUE THREAD

**Issue by katsanva** [nmaro/ooth#49]
Hi @nmaro. What about to have programmatic API for `ooth` alongside HTTP? 

That will allow creating `ooth`-based services that can communicate not only by HTTP, but any transporter (e.g [WebSocket](https://socket.io/), [RabbitMQ](https://www.rabbitmq.com/), [NATS](https://nats.io/), etc) and with the power of any framework (e.g. [seneca](http://senecajs.org/), [moleculer](https://moleculer.services/), [sails](https://sailsjs.com/), [koa](http://koajs.com/), etc.).

In this way, current HTTP API, which is now hard tied to [express](https://expressjs.com/), may become an [express router](https://expressjs.com/en/4x/api.html#router) which uses programmatic API internally.

As far of now I can't find any way to integrate ooth with some existing code base than make [`fetch`](https://github.com/bitinn/node-fetch)/[`request`](https://github.com/request/request) to `ooth`'s HTTP endpoint, and that looks like a pretty strange (and expensive in latency) solution.

**Comment by aaronmgdr** [comment]
I like this

**Comment by nmaro** [comment]
Hey @katsanva since I believe this will generate a major release I think we need to discuss the details a bit more.

Ooth is coupled to express, because it is coupled to passport.js which injects the user in the request and session. I think I need a better idea of where you want to make the decoupling cut. Could give some examples of 

* methods that you would like to call on such a programmatic API (and what they would do).
* What you would give to the `ooth` constructor instead of an express app.

A note: the express app provided to ooth is used to

* register a few global middlewares (`cookieParser`, `bodyParser`, `passport` and `expressWs`)
* register `express.Router` to which all routes are registered (methods called are `all`, `get`, `ws`, `post`).

**Comment by katsanva** [comment]
Hey, @nmaro 

Its all about to decouple oooh from express and HTTP protocol only. 

The idea is to make same API to HTTP one, like `POST /local/register` -> `ooth.local.register()` and so on. Going this way to create an instance you need only to define what strategies should `ooth` use and what backend for users to use.

It may be the best way to re-use passport strategies without actual `passport.js` usage.

The `express` usage may persist in some `ooth-express` package, which will only call `ooth.local.register()` and so on under the hood.

**Comment by nmaro** [comment]
Now every method registered with 

`ooth.registerMethod` can be called with `ooth.callMethod`

For example with `ooth-local` it is now possible to run

`ooth.on('register', ({_id, email, verificationToken}) => ...))`

`await ooth.callMethod('local', 'register', { email, password })`

If this doesn't satisfy all your use cases just let me know, I'll close this for now.
