### ISSUE TITLE
Passworless login using Twillio

### ISSUE THREAD

**Issue by cesarvarela** [nmaro/ooth#75]
I need to support passwordless logins via SMS, would it be too complicated to add support for it?

Where should I start?

**Comment by nmaro** [comment]
Hey @cesarvarela hit me up on [slack](https://join.slack.com/t/ooth/shared_invite/enQtMjQ3MDE2ODA2NjE0LTE1NGNmN2YzZTdiMWNjODExZmNjYzg3ZGJjZmVmZmI2YjVhOWYzZDQ1NWI4Y2JiNzNlMmI2Y2U5ZWFhODIzMWQ) so we can chat real time.

**Comment by nmaro** [comment]
Hey I got inspired and implemented a strategy for authy/twilio, check out the docs here: https://nmaro.github.io/ooth/#authy-twilio

Since you will be the first to use it please review the implementation (it's 1 file): https://github.com/nmaro/ooth/blob/master/packages/ooth-authy/src/index.ts. I'm happy for a pr if you think it can be improved.
